// ── Types (runtime-safe, re-exported as values via type aliases) ──

export type TransactionType = 'income' | 'expense' | 'transfer';

export type AccountGroup =
  | 'Cash'
  | 'Bank Accounts'
  | 'Credit Card'
  | 'Card'
  | 'Debit Card'
  | 'Savings'
  | 'Top-Up/Prepaid'
  | 'Investments'
  | 'Overdrafts'
  | 'Loan'
  | 'Insurance'
  | 'Others';

export interface ITransaction {
  id: string;
  type: TransactionType;
  amount: number;
  date: string; // ISO string
  category: string; // Category ID
  accountId: string; // Account ID
  toAccountId?: string; // Optional for transfers
  note: string;
  description: string;
  attachment?: string; // Base64 image
  recurringId?: string; // Reference to recurring transaction if generated by one
  superCategory?: 'needs' | 'wants' | 'investment' | ''; // Optional super category
  isSettled?: boolean; // For split transactions
  createdAt?: number; // Timestamp for tie-breaking chronological sorts
}

export interface IGoal {
  id: string;
  name: string;
  targetAmount: number;
  currentAmount: number;
  deadline?: string;
  color: string;
  icon?: string;
}

export interface IRecurringTransaction {
  id: string;
  type: TransactionType;
  amount: number;
  categoryId: string;
  accountId: string;
  toAccountId?: string;
  note: string;
  description: string;
  superCategory?: 'needs' | 'wants' | 'investment' | '';
  frequency: 'daily' | 'weekly' | 'monthly' | 'yearly';
  startDate: string;
  nextRunDate: string;
}

export interface IBudget {
  id: string;
  categoryId: string; // 'overall' for total budget, or specific category ID
  amount: number;
  yearMonth: string; // e.g., '2026-08'
}

export interface IAccount {
  id: string;
  name: string;
  group: AccountGroup;
  balance: number;
  settlementDate: number;
  paymentDate: number;
}

export interface ICategory {
  id: string;
  name: string;
  icon: string;
  type: 'income' | 'expense';
}
